#!/bin/bash

echo -e "First type of cycle for : \n"

for car in Toyota Chevrolet LADA
do
echo $car
done

echo -e "\n =============== \n"

echo -e "Second type of cycle for : \n"


for doc in /*
do
if [ -d "$doc" ]
then
echo "$doc - это папка"
elif [ -f "$doc" ]
then
echo "$doc  - это файл"
fi
done

echo -e "\n =============== \n"


echo -e "Third type of cycle for : \n"

for (( i=1; i <= 4; i++ ))
do
echo "number is $i"
	for (( j=1;j <3; j++ ))
	do
	echo -e "\t subnumber is $j"
	done
done
